swagger: '2.0'
info:
  title: Failing spec
  description: Failing spec
  version: '0.0.2'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /:
    post:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/OpStatus'
      responses:
        '200':
          description: 200
          schema:
            type: array
            items:
              $ref: '#/definitions/OpStatus'


definitions:

  OpStatus:
    type: string
    enum: [ "Status One", "Status Two", "Status Three" ]
